import Verso
import VersoManual
import VersoBlueprint
import VirasoroProject.VermaModule
import VirasoroProject.LieVerma
import VirasoroProject.VirasoroVerma
import VirasoroBlueprint.TeXPrelude

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "Verma modules" =>

# A generalized notion of Verma modules

:::definition "def:VermaModule" (lean := "VirasoroProject.VermaModule, VirasoroProject.instModuleVermaModule")
*Generalized Verma module.*
Let $`A` be an algebra over a commutative ring $`\bbk`.
Let $`\eta = (a_i, r_i)_{i \in I} \in (A \times \bbk)^I`
be a family of pairs of algebra elements $`a_i \in A` and
scalars $`r_i \in \bbk`.
The generalized *Verma module* associated to the data $`\eta`
is the quotient

$$`\begin{aligned}
    \Verma^{\eta} = A / J^{\eta} ,
\end{aligned}`

where $`J^{\eta} \subset A`  is the left ideal (an $`A`-submodule) of $`A`
generated by the elements $`a_i - r_i \, 1 \in A`.
Note that $`\Verma^{\eta}` is a (left) $`A`-module.
:::

:::lemma_ "def:HighestWeightVector" (uses := "def:VermaModule") (lean := "VirasoroProject.VermaModule.hwVec, VirasoroProject.VermaModule.hwVec_cyclic, VirasoroProject.VermaModule.apply_hwVec_eq")
*The highest weight vector of a Verma module.*
The vector $`\VermaHWV^{\eta} := 1 + J^{\eta} \in \Verma^{\eta}`
(the equivalence class of the unit element of $`A`)
is called the *highest weight vector* of $`\Verma^{\eta}`.
It is cyclic, i.e., it generates the whole Verma module $`\VermaHWV^{\eta}`
as an $`A`-module, and it satisfies

$$`\begin{aligned}
    a_i \cdot \VermaHWV^{\eta} = r_i \, \VermaHWV^{\eta}
\end{aligned}`

for all $`i \in I`, where $`a_i \in A` and $`r_i \in \bbk`
are the algebra elements and scalars in the collection
$`\eta = (a_i, r_i)_{i \in I}`.
:::

:::proof "def:HighestWeightVector"
Clear from the construction.
:::

:::lemma_ "lem:VermaUniversalProperty" (uses := "def:VermaModule, def:HighestWeightVector") (lean := "VirasoroProject.VermaModule.universalMap, VirasoroProject.VermaModule.universalMap_hwVec, VirasoroProject.VermaModule.range_universalMap_eq_span")
*Universal property of the Verma module.*
Suppose that $`M` is an $`A`-module and $`v \in M` is a vector such that

$$`\begin{aligned}
    a_i \cdot v = r_i \, v
\end{aligned}`

for all $`i \in I`, where $`a_i \in A` and $`r_i \in \bbk` are the algebra elements and scalars in
the collection $`\eta = (a_i, r_i)_{i \in I}`. Then there exists a (unique)
$`A`-module homomorphism $`\phi \colon \Verma^{\eta} \to M` such that
$`\phi(\VermaHWV^{\eta}) = v`. The range of the map $`\phi` is the submodule
generated by $`v` in $`M`.
:::

:::proof "lem:VermaUniversalProperty"
By cyclicity of the highest weight vector $`\VermaHWV^{\eta}`,
any element of $`\Verma^{\eta}` can be written as $`a \cdot \VermaHWV^{\eta}`
for some $`a \in A`.
The map $`A \to M` given by $`a \mapsto a \cdot v` factors through
the quotient by the ideal $`J^{\eta}` by our assumption on $`v`,
and since $`\Verma^{\eta} = A / J^{\eta}`, we thus get a well-defined map
$`\phi \colon \Verma^{\eta} \to M` with the asserted properties.
:::


# Verma modules for Lie algebras with a triangular decomposition

:::definition "def:TriangularDecomposition" (lean := "VirasoroProject.TriangularDecomposition")
*Triangular decomposition of a Lie algebra.*
Let $`\gLie` be a Lie algebra over $`\bbk`.
A *triangular decomposition* of $`\gLie` is a decomposition

$$`\begin{aligned}
    \gLie = \gLie^0 \oplus \gLie^+ \oplus \gLie^-
\end{aligned}`

of $`\gLie` into a vector space direct sum of three vector subspaces:
*Cartan part (or Cartan subalgebra)* $`\gLie^0\subseteq \gLie`,
the *upper part* $`\gLie^+ \subseteq \gLie`,
and the *lower part* $`\gLie^- \subseteq \gLie`.

(Note that in this definition we do not yet require
$`\gLie^0, \gLie^+, \gLie^- \subseteq \gLie` to be Lie subalgebras,
with the Cartan subalgebra being abelian and the
upper and lower parts being nilpotent. In intended use cases, we
typically have these properties, however.)
:::

:::definition "def:LieVermaModule" (uses := "def:TriangularDecomposition, def:VermaModule") (lean := "VirasoroProject.TriangularDecomposition.VermaHW, VirasoroProject.TriangularDecomposition.instModule𝓤VermaHW, VirasoroProject.TriangularDecomposition.instIsScalarTower𝓤VermaHW")
*Verma module.*
Let $`\gLie` be a Lie algebra over $`\bbk`, with a triangular decomposition
$`\gLie = \gLie^0 \oplus \gLie^+ \oplus \gLie^-`.
Let $`\eta \colon \gLie^0 \to \bbk` be a linear functional on the Cartan
part. Then the *Verma module* associated to the "highest weight"
$`\eta` is the generalized Verma module for the universal enveloping
algebra $`\UEA(\gLie)`, associated with the data
consisting of the pairs
$`(H, \eta(H)) \in \UEA(\gLie) \times \bbk` for $`H \in \gLie^0` and
pairs $`(E,0) \in \UEA(\gLie) \times \bbk` for $`E \in \gLie^+`.
The Verma module is (by a mild abuse of notation)
still denoted by $`\Verma^{\eta}`.
:::


# Virasoro Verma modules

:::definition "def:VirasoroTriangular" (uses := "def:TriangularDecomposition, def:VirasoroBasis") (lean := "VirasoroProject.virasoroTri")
*Triangular decomposition of the Virasoro algebra.*
A triangular decomposition

$$`\begin{aligned}
    \vir = \vir^0 \oplus \vir^+ \oplus \vir^-
\end{aligned}`

of $`\vir` is defined so that $`\vir^0` is spanned by $`L_0, C \in \vir`,
$`\vir^+` is spanned by $`L_n` for $`n > 0`,
and $`\vir^-` is spanned by $`L_n` for $`n < 0`.

(Without further comment, for the Virasoro algebra we always use this
triangular decomposition.)
:::

:::definition "def:VirasoroVermaModule" (uses := "def:VirasoroTriangular, def:LieVermaModule") (lean := "VirasoroProject.VirasoroVerma")
*Virasoro Verma module.*
Let $`c, h \in \bbk`.
The Virasoro Verma module with central charge $`c` and conformal weight $`h`
is the Verma module $`\Verma^{\eta}` associated to the linear functional
$`\eta \colon \vir^0 \to \bbk` with

$$`\begin{aligned}
    \eta(L_0) = h, \quad \eta(C) = c .
\end{aligned}`

We denote the Virasoro Verma module by $`\Verma^{c,h}`.
:::
