/-
Copyright (c) 2025 Kalle Kytölä. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kalle Kytölä
-/
import Mathlib
import VirasoroProject.LieAlgebraModuleUEA

namespace VirasoroProject



section canonical_map_from_a_ring_to_a_submodule_generated_by_a_vector

variable (R : Type*) [Ring R] {M : Type*} [AddCommGroup M] [Module R M]

/-- A surjective module map from a ring to the submodule generated by a given vector. -/
def Ring.smulVectorₗ (m : M) :
    R →ₗ[R] M where
  toFun a := a • m
  map_add' a₁ a₂ := by simp [add_smul]
  map_smul' a₁ a₂ := by simp [mul_smul]

@[simp] lemma Ring.smulVectorₗ_one (m : M) :
    smulVectorₗ R m 1 = m := by
  simp [smulVectorₗ]

lemma Ring.range_smulVectorₗ_eq_span (m : M) :
    LinearMap.range (smulVectorₗ R m) = Submodule.span R {m} := by
  ext v
  rw [show v ∈ Submodule.span R {m} ↔ v ∈ (Submodule.span R {m} : Set M) from Eq.to_iff rfl]
  rw [Submodule.span_singleton_eq_range R m ]
  simp only [LinearMap.mem_range, Set.mem_range]
  rfl

end canonical_map_from_a_ring_to_a_submodule_generated_by_a_vector



section cyclic_vectors

/-- The submodule spanned by the unit `1` of a ring is the whole ring. -/
lemma one_cyclic {R : Type*} [Semiring R] :
    Submodule.span R {(1 : R)} = ⊤ :=
  (Submodule.span_singleton_eq_top_iff R 1).mpr fun a ↦ ⟨a, by simp⟩

/-- A surjective linear map maps any cyclic vector (a vector which generates the whole
module) to a cyclic vector. -/
lemma LinearMap.apply_cyclic_of_cyclic_of_surjective {R : Type*} [Semiring R]
    {M₁ M₂ : Type*} [AddCommGroup M₁] [AddCommGroup M₂] [Module R M₁] [Module R M₂]
    {f : M₁ →ₗ[R] M₂} (f_surj : LinearMap.range f = ⊤)
    (m : M₁) (cyclic : Submodule.span R {m} = ⊤) :
    Submodule.span R {f m} = ⊤ := by
  rw [Submodule.span_singleton_eq_top_iff] at *
  intro m₂
  obtain ⟨m₁, hm⟩ : ∃ m₁, f m₁ = m₂ := LinearMap.range_eq_top.mp f_surj m₂
  obtain ⟨a, ha⟩ := cyclic m₁
  refine ⟨a, by rw [← map_smul, ha, hm]⟩

end cyclic_vectors



section generalized_Verma_module

variable {𝕜 A : Type*} [CommRing 𝕜] [Ring A] [Algebra 𝕜 A]
variable {ι : Type*}

/-- The left ideal used in the construction of a (generalized) Verma module for an algebra `A`:
`η : ι → A × 𝕜` is an indexed collection of algebra elements and scalars by which they should act
on the "highest weight vector". -/
def vermaIdeal (η : ι → A × 𝕜) :
    Submodule A A :=
  Submodule.span A (Set.range <| fun (i : ι) ↦ (η i).1 - algebraMap 𝕜 A (η i).2)

/-- The (generalied) Verma module of an algebra `A`:
`η : ι → A × 𝕜` is an indexed collection of algebra elements and scalars by which they should act
on the "highest weight vector". -/
def VermaModule (η : ι → A × 𝕜) :=
  A ⧸ vermaIdeal η

/-- The highest weight vector in a (generalized) Verma module. -/
def VermaModule.hwVec (η : ι → A × 𝕜) :
    VermaModule η :=
  Submodule.Quotient.mk 1

instance (η : ι → A × 𝕜) :
    AddCommGroup (VermaModule η) :=
  Submodule.Quotient.addCommGroup _

instance (η : ι → A × 𝕜) :
    Module A (VermaModule η) :=
  Submodule.Quotient.module _

/-- The highest weight vector in a Verma module is cyclic. -/
lemma VermaModule.hwVec_cyclic (η : ι → A × 𝕜) :
    Submodule.span A {hwVec η} = ⊤ :=
  LinearMap.apply_cyclic_of_cyclic_of_surjective (Submodule.range_mkQ _) 1 one_cyclic

/-- The defining property of the highest weight vector in a Verma module. -/
lemma VermaModule.apply_hwVec_eq (η : ι → A × 𝕜) (i : ι) :
    (η i).1 • hwVec η = (algebraMap 𝕜 A (η i).2) • hwVec η := by
  rw [show (algebraMap 𝕜 A (η i).2) • hwVec η
            = Submodule.Quotient.mk ((algebraMap 𝕜 A (η i).2) • 1) from rfl]
  rw [hwVec, ← Submodule.Quotient.mk_smul, ← sub_eq_zero, ← Submodule.Quotient.mk_sub]
  apply (Submodule.Quotient.mk_eq_zero ..).mpr
  exact Submodule.mem_span_of_mem (by simp)

variable {M : Type*} [AddCommGroup M] [Module A M]

lemma vermaIdeal_le_ker_smulVectorₗ (η : ι → A × 𝕜)
    {hwv : M} (hwv_prop : ∀ i, (η i).1 • hwv = algebraMap 𝕜 A (η i).2 • hwv) :
    vermaIdeal η ≤ LinearMap.ker (Ring.smulVectorₗ A hwv) := by
  simp only [vermaIdeal, Submodule.span_le]
  intro a ⟨i, a_eq⟩
  simp only [← a_eq, SetLike.mem_coe, LinearMap.mem_ker, map_sub, sub_eq_zero]
  exact hwv_prop i

/-- The map guaranteed by the universal property of a Verma module. -/
def VermaModule.universalMap (η : ι → A × 𝕜)
    {hwv : M} (hwv_prop : ∀ i, (η i).1 • hwv = algebraMap 𝕜 A (η i).2 • hwv) :
    VermaModule η →ₗ[A] M :=
  Submodule.liftQ (vermaIdeal η) (Ring.smulVectorₗ A hwv) (vermaIdeal_le_ker_smulVectorₗ _ hwv_prop)

/-- The image of the highest weight vector of a Verma module under the map guaranteed by the
universal property is the assigned highest weight vector in the image module. -/
@[simp] lemma VermaModule.universalMap_hwVec (η : ι → A × 𝕜)
    {hwv : M} (hwv_prop : ∀ i, (η i).1 • hwv = algebraMap 𝕜 A (η i).2 • hwv) :
    universalMap η hwv_prop (hwVec η) = hwv := by
  convert Submodule.liftQ_apply (vermaIdeal η) (Ring.smulVectorₗ A hwv) 1
  simp

/-- The range of the map guaranteed by the universal property of a Verma module is the submodule
generated by the assigned highest weight vector in the image module. -/
lemma VermaModule.range_universalMap_eq_span (η : ι → A × 𝕜)
    {hwv : M} (hwv_prop : ∀ i, (η i).1 • hwv = algebraMap 𝕜 A (η i).2 • hwv) :
    LinearMap.range (universalMap η hwv_prop) = Submodule.span A {hwv} := by
  have key := VermaModule.hwVec_cyclic η ▸ Submodule.map_top (universalMap η hwv_prop)
  simp [← key, Submodule.map_span]

end generalized_Verma_module


end VirasoroProject
